# Generated by Django 4.0.3 on 2022-10-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companines'},
        ),
        migrations.AlterField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advocates', to='api.company'),
        ),
        migrations.AlterField(
            model_name='link',
            name='advocate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.advocate'),
        ),
    ]
