# Generated by Django 4.1.2 on 2022-10-16 11:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options_alter_advocate_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/advocate', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='images/company'),
        ),
    ]
