# Generated by Django 4.1.2 on 2022-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_advocate_profile_pic_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
